export const MAIN_LABELS = {
  caloryData: {
    amr: "일일 권장 칼로리(활동 대사량)",
    total: "현재까지 섭취 칼로리",
  },
  avg: {
    bmi: "비만도",
    bmr: "기초대사량",
    weight: "체중",
  },
  userAvg: {
    bmi: "나의 비만도",
    bmr: "나의 기초대사량",
  },
};

export const MEAL_ITEM_TITLE = {
  menu: "메뉴",
  weight: "중량",
  calory: "칼로리",
  carbs: "탄수화물",
  protein: "단백질",
  fat: "지방",
  total: "총 칼로리",
};

export const CATEGORY_ITEMS = {
  processed: [
    { did: 1, id: 1, name: "과자,빵, 떡류", table: "snack_bread_rice" },
    { did: 1, id: 2, name: "빙과류", table: "ice" },
    { did: 1, id: 3, name: "코코아, 초코류", table: "chocolate" },
    { did: 1, id: 4, name: "당류", table: "sugar" },
    { did: 1, id: 5, name: "잼류", table: "jam" },
    { did: 1, id: 6, name: "두부, 묵류", table: "tofu_jello" },
    { did: 1, id: 7, name: "식용유지류", table: "oil" },
    { did: 1, id: 8, name: "면류", table: "noodle" },
    { did: 1, id: 9, name: "음료류", table: "drink" },
    { did: 1, id: 10, name: "장류", table: "paste" },
    { did: 1, id: 11, name: "조미료, 소스류", table: "seasoned" },
    { did: 1, id: 12, name: "절임, 조림류", table: "pickle_braise" },
    { did: 1, id: 13, name: "농산가공식품류", table: "agricultural" },
    { did: 1, id: 14, name: "식육가공품, 포장육", table: "meat" },
    { did: 1, id: 15, name: "알가공품류", table: "egg" },
    { did: 1, id: 16, name: "유제품류", table: "milk" },
    { did: 1, id: 17, name: "수산가공식품류", table: "fish" },
    { did: 1, id: 18, name: "동물성가공식품류", table: "animal" },
    { did: 1, id: 19, name: "냉동 및 즉석식품류", table: "instant" },
    { did: 1, id: 20, name: "기타식품류", table: "etc" },
  ],
  in: [
    { did: 2, id: 21, name: "밥류", table: "rice" },
    { did: 2, id: 22, name: "빵, 과자류", table: "snack_bread" },
    { did: 2, id: 23, name: "면, 만두류", table: "noodle_dumpling" },
    { did: 2, id: 24, name: "죽, 스프류", table: "braised_soup" },
    { did: 2, id: 25, name: "국, 탕류", table: "soup" },
    { did: 2, id: 26, name: "찌개, 전골류", table: "hot_pot" },
    { did: 2, id: 27, name: "찜류", table: "steamed" },
    { did: 2, id: 28, name: "구이류", table: "griled" },
    { did: 2, id: 29, name: "전, 적, 부침류", table: "pancake" },
    { did: 2, id: 30, name: "볶음류", table: "stir_fried" },
    { did: 2, id: 31, name: "조림류", table: "braised" },
    { did: 2, id: 32, name: "튀김류", table: "fried" },
    { did: 2, id: 33, name: "나물, 숙채류", table: "vege" },
    { did: 2, id: 34, name: "생채, 무침류", table: "raw_vege" },
    { did: 2, id: 35, name: "김치류", table: "kimchi" },
    { did: 2, id: 36, name: "젓갈류", table: "salted_fish" },
    { did: 2, id: 37, name: "장아찌, 절임류", table: "pickle" },
    { did: 2, id: 38, name: "음료, 차류", table: "drink" },
    { did: 2, id: 39, name: "(수,조,어,육)류", table: "raw_meat" },
  ],
  out: [
    { did: 3, id: 21, name: "밥류", table: "rice" },
    { did: 3, id: 22, name: "빵, 과자류", table: "snack_bread" },
    { did: 3, id: 23, name: "면, 만두류", table: "noodle_dumpling" },
    { did: 3, id: 24, name: "죽, 스프류", table: "braised_soup" },
    { did: 3, id: 25, name: "국, 탕류", table: "soup" },
    { did: 3, id: 26, name: "찌개, 전골류", table: "hot_pot" },
    { did: 3, id: 27, name: "찜류", table: "steamed" },
    { did: 3, id: 28, name: "구이류", table: "griled" },
    { did: 3, id: 29, name: "전, 적, 부침류", table: "pancake" },
    { did: 3, id: 30, name: "볶음류", table: "stir_fried" },
    { did: 3, id: 31, name: "조림류", table: "braised" },
    { did: 3, id: 32, name: "튀김류", table: "fried" },
    { did: 3, id: 33, name: "나물, 숙채류", table: "vege" },
    { did: 3, id: 34, name: "샐러드, 생채, 무침류", table: "raw_vege" },
    { did: 3, id: 35, name: "김치류", table: "kimchi" },
    { did: 3, id: 36, name: "젓갈류", table: "salted_fish" },
    { did: 3, id: 37, name: "장아찌, 절임류", table: "pickle" },
    { did: 3, id: 38, name: "음료, 차류", table: "drink" },
    { did: 3, id: 40, name: "장, 양념류", table: "paste_seasoning" },
    { did: 3, id: 41, name: "유제품, 빙과류", table: "dairy_ice" },
    { did: 3, id: 42, name: "과일류", table: "fruits" },
    { did: 3, id: 43, name: "곡류, 서류", table: "cereals_tubers" },
    { did: 3, id: 44, name: "계란/알류", table: "egg" },
  ],
};
