export const MAIN_LABELS = {
  caloryData: {
    amr: "일일 권장 칼로리(활동 대사량)",
    total: "현재까지 섭취 칼로리",
  },
  avg: {
    bmi: "비만도",
    bmr: "기초대사량",
    weight: "체중",
  },
  userAvg: {
    bmi: "나의 비만도",
    bmr: "나의 기초대사량",
  },
};

export const MEAL_ITEM_TITLE = {
  menu: "메뉴",
  weight: "중량",
  calory: "칼로리",
  carbs: "탄수화물",
  protein: "단백질",
  fat: "지방",
  total: "총 칼로리",
};

export const CATEGORY_ITEMS = {
  processed: [
    { id: 1, did: 1, name: "과자,빵, 떡류", table: "snack_bread_rice" },
    { id: 2, did: 1, name: "빙과류", table: "ice" },
    { id: 3, did: 1, name: "코코아, 초코류", table: "chocolate" },
    { id: 4, did: 1, name: "당류", table: "sugar" },
    { id: 5, did: 1, name: "잼류", table: "jam" },
    { id: 6, did: 1, name: "두부, 묵류", table: "tofu_jello" },
    { id: 7, did: 1, name: "식용유지류", table: "oil" },
    { id: 8, did: 1, name: "면류", table: "noodle" },
    { id: 9, did: 1, name: "음료류", table: "drink" },
    { id: 10, did: 1, name: "장류", table: "paste" },
    { id: 11, did: 1, name: "조미식품", table: "seasoned" },
    { id: 12, did: 1, name: "절임, 조림류", table: "pickle_braise" },
    { id: 13, did: 1, name: "주류", table: "alcohol" },
    { id: 14, did: 1, name: "농산가공식품류", table: "agricultural" },
    { id: 15, did: 1, name: "식육가공품, 포장육", table: "meat" },
    { id: 16, did: 1, name: "알가공품류", table: "egg" },
    { id: 17, did: 1, name: "유가공품류", table: "milk" },
    { id: 18, did: 1, name: "수산가공식품류", table: "fish" },
    { id: 19, did: 1, name: "동물성가공식품류", table: "animal" },
    { id: 20, did: 1, name: "즉석식품류", table: "instant" },
    { id: 21, did: 1, name: "기타식품류", table: "etc" },
  ],
  in: [
    { id: 22, did: 2, name: "밥류", table: "rice" },
    { id: 23, did: 2, name: "빵, 과자류", table: "snack_bread" },
    { id: 24, did: 2, name: "면, 만두류", table: "noodle_dumpling" },
    { id: 25, did: 2, name: "죽, 스프류", table: "braised_soup" },
    { id: 26, did: 2, name: "국, 탕류", table: "soup" },
    { id: 27, did: 2, name: "찌개, 전골류", table: "hot_pot" },
    { id: 28, did: 2, name: "찜류", table: "steamed" },
    { id: 29, did: 2, name: "구이류", table: "griled" },
    { id: 30, did: 2, name: "전, 적, 부침류", table: "pancake" },
    { id: 31, did: 2, name: "볶음류", table: "stir_fried" },
    { id: 32, did: 2, name: "조림류", table: "braised" },
    { id: 33, did: 2, name: "튀김류", table: "fried" },
    { id: 34, did: 2, name: "나물, 숙채류", table: "vege" },
    { id: 35, did: 2, name: "생채, 무침류", table: "raw_vege" },
    { id: 36, did: 2, name: "김치류", table: "kimchi" },
    { id: 37, did: 2, name: "젓갈류", table: "salted_fish" },
    { id: 38, did: 2, name: "장아찌, 절임류", table: "pickle" },
    { id: 39, did: 2, name: "음료, 차류", table: "drink" },
    { id: 40, did: 2, name: "(수,조,어,육)류", table: "raw_meat" },
  ],
  out: [
    { id: 41, did: 3, name: "밥류", table: "rice" },
    { id: 42, did: 3, name: "빵, 과자류", table: "snack_bread" },
    { id: 43, did: 3, name: "면, 만두류", table: "noodle_dumpling" },
    { id: 44, did: 3, name: "죽, 스프류", table: "braised_soup" },
    { id: 45, did: 3, name: "국, 탕류", table: "soup" },
    { id: 46, did: 3, name: "구이류", table: "griled" },
    { id: 47, did: 3, name: "볶음류", table: "stir_fried" },
    { id: 48, did: 3, name: "조림류", table: "steamed" },
    { id: 49, did: 3, name: "튀김류", table: "fried" },
    { id: 50, did: 3, name: "생채, 무침류", table: "raw_vege" },
    { id: 51, did: 3, name: "장류, 양념류", table: "paste_seasoned" },
    { id: 52, did: 3, name: "유제품, 빙과류", table: "milk_ice" },
    { id: 53, did: 3, name: "음료, 차류", table: "drink" },
    { id: 54, did: 3, name: "과일류", table: "fruit" },
    { id: 55, did: 3, name: "곡류, 서류", table: "grain" },
    { id: 56, did: 3, name: "찌개, 전골류", table: "hot_pot" },
    { id: 57, did: 3, name: "찜류", table: "steamed" },
    { id: 58, did: 3, name: "전, 적, 부침류", table: "pancake" },
    { id: 59, did: 3, name: "나물, 숙채류", table: "vege" },
    { id: 60, did: 3, name: "김치류", table: "kimchi" },
    { id: 61, did: 3, name: "젓갈류", table: "salted_fish" },
    { id: 62, did: 3, name: "장아찌, 절임류", table: "pickle" },
    { id: 63, did: 3, name: "알류", table: "egg" },
  ],
};
